=== FabricioLanche/Chinawok-DataGenerator/schemas-validation/empleados.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Empleados",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "local_id",
    "sort_key": "dni"
  },
  "properties": {
    "local_id": { "type": "string" },
    "dni": { "type": "string" },
    "nombre": { "type": "string" },
    "apellido": { "type": "string" },
    "calificacion_prom": { "type": "number", "minimum": 0, "maximum": 5 },
    "sueldo": { "type": "number", "minimum": 0 },
    "role": { "type": "string", "enum": ["Repartidor", "Cocinero", "Despachador"] }
  },
  "required": ["local_id", "dni", "nombre", "apellido", "role"],
  "additionalProperties": false
}

=== FabricioLanche/Chinawok-DataGenerator/dynamodb_data/empleados.json
[
  {
    "local_id": "LOCAL-0001",
    "dni": "45696828",
    "nombre": "Andrea",
    "apellido": "Vargas",
    "role": "Repartidor",
    "calificacion_prom": 4.41,
    "sueldo": 2082.27
  },
  {
    "local_id": "LOCAL-0001",
    "dni": "49721736",
    "nombre": "Carmen",
    "apellido": "Gutiérrez",
    "role": "Despachador",
    "calificacion_prom": 4.12,
    "sueldo": 2565.24
  },
  {
    "local_id": "LOCAL-0001",
    "dni": "22892307",
    "nombre": "Alberto",
    "apellido": "Ramírez",
    "role": "Repartidor",
    "calificacion_prom": 4.54,
    "sueldo": 2777.86
  },
  {
    "local_id": "LOCAL-0001",
    "dni": "27702363",
    "nombre": "Pedro",
    "apellido": "Reyes",
    "role": "Repartidor",
    "calificacion_prom": 3.86,
    "sueldo": 2798.35
  },
  {
    "local_id": "LOCAL-0001",
    "dni": "34527553",
    "nombre": "Roberto",
    "apellido": "Rivera",
    "role": "Despachador",
    "calificacion_prom": 3.65,
    "sueldo": 2022.56
  },
  {
    "local_id": "LOCAL-0002",
    "dni": "75621894",
    "nombre": "Rosa",
    "apellido": "Gómez",
    "role": "Cocinero",
    "calificacion_prom": 4.72,
    "sueldo": 2161.94
  },
  {
    "local_id": "LOCAL-0002",
    "dni": "66329793",
    "nombre": "Miguel",
    "apellido": "Cruz",
    "role": "Despachador",
    "calificacion_prom": 3.9,
    "sueldo": 1864.6
  },
  {
    "local_id": "LOCAL-0002",
    "dni": "56282938",
    "nombre": "Alberto",
    "apellido": "Gutiérrez",
    "role": "Despachador",
    "calificacion_prom": 4.08,
    "sueldo": 1464.55
  },
  {
    "local_id": "LOCAL-0002",
    "dni": "41747950",
    "nombre": "Sofía",
    "apellido": "Castillo",
    "role": "Despachador",
    "calificacion_prom": 4.89,
    "sueldo": 1825.36
  },
  {
    "local_id": "LOCAL-0002",
    "dni": "86553733",
    "nombre": "Isabel",
    "apellido": "Díaz",
    "role": "Despachador",
    "calificacion_prom": 3.72,
    "sueldo": 2017.13
  },
  {
    "local_id": "LOCAL-0003",
    "dni": "25404544",
    "nombre": "Ricardo",
    "apellido": "Jiménez",
    "role": "Cocinero",
    "calificacion_prom": 3.71,
    "sueldo": 2458.88
  },
  {
    "local_id": "LOCAL-0003",
    "dni": "23101988",
    "nombre": "Camila",
    "apellido": "Ortiz",
    "role": "Despachador",
    "calificacion_prom": 4.6,
    "sueldo": 2609.81
  },
  {
    "local_id": "LOCAL-0003",
    "dni": "60092618",
    "nombre": "Roberto",
    "apellido": "Gómez",
    "role": "Repartidor",
    "calificacion_prom": 4.29,
    "sueldo": 1495.82
  },
  {
    "local_id": "LOCAL-0003",
    "dni": "67301207",
    "nombre": "Alberto",
    "apellido": "Vargas",
    "role": "Cocinero",
    "calificacion_prom": 4.16,
    "sueldo": 2393.44
  },
  {
    "local_id": "LOCAL-0003",
    "dni": "82154462",
    "nombre": "Andrea",
    "apellido": "Vargas",
    "role": "Repartidor",
    "calificacion_prom": 4.55,
    "sueldo": 2654.81
  },
  {
    "local_id": "LOCAL-0004",
    "dni": "94966760",
    "nombre": "Jorge",
    "apellido": "Vargas",
    "role": "Cocinero",
    "calificacion_prom": 3.96,
    "sueldo": 2610.3
  },
  {
    "local_id": "LOCAL-0004",
    "dni": "54072156",
    "nombre": "Diego",
    "apellido": "Cruz",
    "role": "Despachador",
    "calificacion_prom": 3.97,
    "sueldo": 1861.32
  },
  {
    "local_id": "LOCAL-0004",
    "dni": "91244994",
    "nombre": "Isabel",
    "apellido": "Sánchez",
    "role": "Despachador",
    "calificacion_prom": 4.65,
    "sueldo": 1383.15
  },
  {
    "local_id": "LOCAL-0004",
    "dni": "90968897",
    "nombre": "Miguel",
    "apellido": "Rodríguez",
    "role": "Despachador",
    "calificacion_prom": 4.85,
    "sueldo": 2177.92
  },
  {
    "local_id": "LOCAL-0004",
    "dni": "13419356",
    "nombre": "Rosa",
    "apellido": "Flores",
    "role": "Despachador",
    "calificacion_prom": 4.82,
    "sueldo": 1522.04
  },
  {
    "local_id": "LOCAL-0005",
    "dni": "92223425",
    "nombre": "Sofía",
    "apellido": "Gómez",
    "role": "Despachador",
    "calificacion_prom": 4.27,
    "sueldo": 2772.36
  },
  {
    "local_id": "LOCAL-0005",
    "dni": "41079174",
    "nombre": "Juan",
    "apellido": "González",
    "role": "Repartidor",
    "calificacion_prom": 4.14,
    "sueldo": 2604.34
  },
  {
    "local_id": "LOCAL-0005",
    "dni": "75754533",
    "nombre": "Roberto",
    "apellido": "Flores",
    "role": "Cocinero",
    "calificacion_prom": 4.0,
    "sueldo": 2044.47
  },
  {
    "local_id": "LOCAL-0005",
    "dni": "24845730",
    "nombre": "Laura",
    "apellido": "Vargas",
    "role": "Repartidor",
    "calificacion_prom": 4.01,
    "sueldo": 2534.09
  },
  {
    "local_id": "LOCAL-0005",
    "dni": "22270205",
    "nombre": "Ana",
    "apellido": "Rivera",
    "role": "Repartidor",
    "calificacion_prom": 4.37,
    "sueldo": 1374.22
  },
  {
    "local_id": "LOCAL-0006",
    "dni": "53060863",
    "nombre": "Elena",
    "apellido": "García",
    "role": "Despachador",
    "calificacion_prom": 3.85,
    "sueldo": 1309.06
  },
  {
    "local_id": "LOCAL-0006",
    "dni": "30279837",
    "nombre": "Camila",
    "apellido": "Torres",
    "role": "Cocinero",
    "calificacion_prom": 4.36,
    "sueldo": 1548.6
  },
  {
    "local_id": "LOCAL-0006",
    "dni": "50165492",
    "nombre": "Diego",
    "apellido": "López",
    "role": "Despachador",
    "calificacion_prom": 4.6,
    "sueldo": 2541.0
  },
  {
    "local_id": "LOCAL-0006",
    "dni": "54009615",
    "nombre": "Jorge",
    "apellido": "Gómez",
    "role": "Despachador",
    "calificacion_prom": 4.71,
    "sueldo": 2067.7
  },
  {
    "local_id": "LOCAL-0006",
    "dni": "27609399",
    "nombre": "Roberto",
    "apellido": "Pérez",
    "role": "Cocinero",
    "calificacion_prom": 4.7,
    "sueldo": 1277.4
  },
  {
    "local_id": "LOCAL-0007",
    "dni": "10641734",
    "nombre": "Carmen",
    "apellido": "Sánchez",
    "role": "Cocinero",
    "calificacion_prom": 4.7,
    "sueldo": 1678.71
  },
  {
    "local_id": "LOCAL-0007",
    "dni": "49599382",
    "nombre": "Carmen",
    "apellido": "García",
    "role": "Despachador",
    "calificacion_prom": 4.53,
    "sueldo": 2550.91
  },
  {
    "local_id": "LOCAL-0007",
    "dni": "95368049",
    "nombre": "Carlos",
    "apellido": "Vargas",
    "role": "Repartidor",
    "calificacion_prom": 3.87,
    "sueldo": 2341.51
  },
  {
    "local_id": "LOCAL-0007",
    "dni": "80055318",
    "nombre": "Carmen",
    "apellido": "Mendoza",
    "role": "Repartidor",
    "calificacion_prom": 4.61,
    "sueldo": 2523.06
  },
  {
    "local_id": "LOCAL-0007",
    "dni": "42747186",
    "nombre": "Rosa",
    "apellido": "Rivera",
    "role": "Cocinero",
    "calificacion_prom": 4.79,
    "sueldo": 2315.57
  },
  {
    "local_id": "LOCAL-0008",
    "dni": "31504549",
    "nombre": "Luis",
    "apellido": "Romero",
    "role": "Despachador",
    "calificacion_prom": 4.13,
    "sueldo": 1524.63
  },
  {
    "local_id": "LOCAL-0008",
    "dni": "82026798",
    "nombre": "Miguel",
    "apellido": "Gómez",
    "role": "Despachador",
    "calificacion_prom": 3.77,
    "sueldo": 2104.93
  },
  {
    "local_id": "LOCAL-0008",
    "dni": "95609961",
    "nombre": "Rosa",
    "apellido": "Martínez",
    "role": "Cocinero",
    "calificacion_prom": 4.33,
    "sueldo": 2091.37
  },
  {
    "local_id": "LOCAL-0008",
    "dni": "98617561",
    "nombre": "Roberto",
    "apellido": "Gómez",
    "role": "Repartidor",
    "calificacion_prom": 4.89,
    "sueldo": 2274.78
  },
  {
    "local_id": "LOCAL-0008",
    "dni": "97811825",
    "nombre": "Juan",
    "apellido": "Cruz",
    "role": "Cocinero",
    "calificacion_prom": 4.89,
    "sueldo": 1439.81
  },
  {
    "local_id": "LOCAL-0009",
    "dni": "49517743",
    "nombre": "Andrea",
    "apellido": "Vargas",
    "role": "Repartidor",
    "calificacion_prom": 4.37,
    "sueldo": 2753.3
  },
  {
    "local_id": "LOCAL-0009",
    "dni": "32483110",
    "nombre": "Elena",
    "apellido": "Cruz",
    "role": "Repartidor",
    "calificacion_prom": 4.54,
    "sueldo": 2936.63
  },
  {
    "local_id": "LOCAL-0009",
    "dni": "61532958",
    "nombre": "Daniela",
    "apellido": "Cruz",
    "role": "Cocinero",
    "calificacion_prom": 3.52,
    "sueldo": 2904.03
  },
  {
    "local_id": "LOCAL-0009",
    "dni": "16767450",
    "nombre": "Andrea",
    "apellido": "Pérez",
    "role": "Repartidor",
    "calificacion_prom": 4.17,
    "sueldo": 1477.06
  },
  {
    "local_id": "LOCAL-0009",
    "dni": "34597113",
    "nombre": "Patricia",
    "apellido": "Herrera",
    "role": "Repartidor",
    "calificacion_prom": 4.44,
    "sueldo": 2907.61
  },
  {
    "local_id": "LOCAL-0010",
    "dni": "78872403",
    "nombre": "Juan",
    "apellido": "Vargas",
    "role": "Repartidor",
    "calificacion_prom": 5.0,
    "sueldo": 2071.25
  },
  {
    "local_id": "LOCAL-0010",
    "dni": "75671955",
    "nombre": "Lucía",
    "apellido": "Flores",
    "role": "Despachador",
    "calificacion_prom": 4.48,
    "sueldo": 2380.06
  },
  {
    "local_id": "LOCAL-0010",
    "dni": "90053841",
    "nombre": "José",
    "apellido": "Flores",
    "role": "Repartidor",
    "calificacion_prom": 3.93,
    "sueldo": 2764.77
  },
  {
    "local_id": "LOCAL-0010",
    "dni": "31254139",
    "nombre": "Isabel",
    "apellido": "Ramírez",
    "role": "Despachador",
    "calificacion_prom": 3.72,
    "sueldo": 2504.88
  },
  {
    "local_id": "LOCAL-0010",
    "dni": "24878094",
    "nombre": "Ricardo",
    "apellido": "Herrera",
    "role": "Cocinero",
    "calificacion_prom": 3.52,
    "sueldo": 2345.34
  },
  {
    "local_id": "LOCAL-0011",
    "dni": "66759715",
    "nombre": "Elena",
    "apellido": "Cruz",
    "role": "Despachador",
    "calificacion_prom": 3.86,
    "sueldo": 2539.67
  },
  {
    "local_id": "LOCAL-0011",
    "dni": "64448990",
    "nombre": "Sofía",
    "apellido": "González",
    "role": "Cocinero",
    "calificacion_prom": 4.05,
    "sueldo": 2516.78
  },
  {
    "local_id": "LOCAL-0011",
    "dni": "47914982",
    "nombre": "Miguel",
